#!/usr/bin/env python3
"""Packs the animated Black/White GIF sprites into PNG sheets plus a metadata module.

usage: pack-anim.py <dir with 1.gif … 151.gif> (needs Pillow)
writes assets/battle/anim/<num>.png (frames on a grid, trimmed to their common bounding box) and
animmeta.js (ANIM_META[num] = { w, h, n, cols, d: [frame durations in ms], b: bottom-most opaque row })
Consecutive identical frames are merged by adding their durations.
"""
import sys, os, json
from PIL import Image, ImageSequence
src = sys.argv[1]; root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
out = os.path.join(root, 'assets', 'battle', 'anim'); os.makedirs(out, exist_ok=True)
meta = {}; total = 0
for num in range(1, 152):
    path = os.path.join(src, f'{num}.gif')
    if not os.path.exists(path): continue
    im = Image.open(path); frames = []
    for fr in ImageSequence.Iterator(im):
        rgba = fr.convert('RGBA'); d = max(20, int(fr.info.get('duration', 100) or 100))
        if frames and list(frames[-1][0].getdata()) == list(rgba.getdata()): frames[-1][1] += d
        else: frames.append([rgba, d])
    # common bounding box over all frames
    box = None
    for f, _ in frames:
        bb = f.getbbox()
        if bb: box = bb if box is None else (min(box[0], bb[0]), min(box[1], bb[1]), max(box[2], bb[2]), max(box[3], bb[3]))
    if box is None: continue
    w, h = box[2] - box[0], box[3] - box[1]; n = len(frames); cols = max(1, int(n ** .5 + .999)); rows = (n + cols - 1) // cols
    sheet = Image.new('RGBA', (cols * w, rows * h), (0, 0, 0, 0)); bottom = 0
    for i, (f, _) in enumerate(frames):
        c = f.crop(box); sheet.paste(c, ((i % cols) * w, (i // cols) * h))
        bb = c.getbbox()
        if bb: bottom = max(bottom, bb[3])
    sheet.save(os.path.join(out, f'{num}.png'), optimize=True)
    total += os.path.getsize(os.path.join(out, f'{num}.png'))
    meta[num] = {'w': w, 'h': h, 'n': n, 'cols': cols, 'd': [d for _, d in frames], 'b': bottom}
with open(os.path.join(root, 'animmeta.js'), 'w') as f:
    f.write('// Generated by tools/pack-anim.py: frame layout of assets/battle/anim/<num>.png (animated Black/White sprites).\n')
    f.write("'use strict';\nconst ANIM_META = " + json.dumps(meta, separators=(',', ':')) + ';\n')
print(f'{len(meta)} sheets, {total / 1e6:.1f} MB, frames {sum(m["n"] for m in meta.values())}')
